name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Grab the code
        uses: actions/checkout@v3

      - name: Load Terraform tools
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: terraform -chdir=terraform init

      - name: Check formatting
        run: terraform -chdir=terraform fmt -check -recursive

      - name: Validate syntax
        run: terraform -chdir=terraform validate